import type { Metadata } from "next";
import { Auth0Provider } from "@auth0/nextjs-auth0/client";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="en" className="h-full antialiased">
        <body className="min-h-full flex flex-col">
            <Auth0Provider>{children}</Auth0Provider>
        </body>
    </html>
  );
}
